//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WaterSimUI {
    
    
    public partial class _Default {
        
        /// <summary>
        /// InputUserControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WaterSimUI.UserControls.InputUserControl InputUserControl1;
        
        /// <summary>
        /// InputUserControl2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WaterSimUI.UserControls.InputUserControl InputUserControl2;
        
        /// <summary>
        /// InputUserControl3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WaterSimUI.UserControls.InputUserControl InputUserControl3;
        
        /// <summary>
        /// OutputControl1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WaterSimUI.UserControls.OutputUserControl OutputControl1;
        
        /// <summary>
        /// OutputControl1a control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WaterSimUI.UserControls.OutputUserControl OutputControl1a;
        
        /// <summary>
        /// OutputControlNON control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WaterSimUI.UserControls.OutputUserControl OutputControlNON;
        
        /// <summary>
        /// OutputControlDEM control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WaterSimUI.UserControls.OutputUserControl OutputControlDEM;
        
        /// <summary>
        /// OutputControl_RainHarvest control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WaterSimUI.UserControls.OutputUserControl OutputControl_RainHarvest;
        
        /// <summary>
        /// OutputControl_GrayWater control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WaterSimUI.UserControls.OutputUserControl OutputControl_GrayWater;
        
        /// <summary>
        /// OutputControl7 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WaterSimUI.UserControls.OutputUserControl OutputControl7;
        
        /// <summary>
        /// OutputControl5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WaterSimUI.UserControls.OutputUserControl OutputControl5;
        
        /// <summary>
        /// OutputControl8B control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WaterSimUI.UserControls.OutputUserControl OutputControl8B;
        
        /// <summary>
        /// OutputControl8C control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WaterSimUI.UserControls.OutputUserControl OutputControl8C;
        
        /// <summary>
        /// OutputControl13 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WaterSimUI.UserControls.OutputUserControl OutputControl13;
        
        /// <summary>
        /// OutputControl10 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WaterSimUI.UserControls.OutputUserControl OutputControl10;
        
        /// <summary>
        /// OutputControl11 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WaterSimUI.UserControls.OutputUserControl OutputControl11;
        
        /// <summary>
        /// OutputControl18 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WaterSimUI.UserControls.OutputUserControl OutputControl18;
        
        /// <summary>
        /// OutputControl14 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::WaterSimUI.UserControls.OutputUserControl OutputControl14;
    }
}
